name: Count Weekly Solved Problems
on:
  schedule:
    - cron: '0 15 * * 0'  # 한국 시간 월요일 00:00 (UTC 일요일 15:00)

jobs:
  count-problems:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0  # 전체 커밋 이력을 가져오기

      - name: Fetch all history
        run: git fetch --all  # 미러링된 변경 사항 반영

      - name: Count problems and update COUNT.md
        run: |
          start_date=$(date -d "last monday -9 hours" +%Y-%m-%d)
          end_date=$(date -d "today -9 hours" +%Y-%m-%d)
          
          week_title=$(date -d "last monday -9 hours" +"%Y년 %-m월 %-d일")
          date_range="(${start_date} ~ $(date -d "yesterday -9 hours" +%Y-%m-%d))"
          
          count_files() {
            local folder=$1
            # git log 대신 git diff 사용하여 변경 사항 확인
            local count=$(git diff --name-only $(git rev-list -n 1 --before="${start_date} 00:00:00" HEAD) HEAD -- "${folder}/*" | grep -E "\.(java|py|js)$" | sort -u | wc -l)
            echo $count
          }

          yhr_count=$(count_files "유하람")
          khb_count=$(count_files "김햇빛")
          lsy_count=$(count_files "이승연")
          owj_count=$(count_files "오완진")
          msh_count=$(count_files "문세희")

          if [ -f COUNT.md ]; then
            cat COUNT.md > temp.md
          fi
          
          {
            echo "# ${week_title} 문제 풀이 현황 ${date_range}"
            echo "* 유하람: ${yhr_count}개"
            echo "* 김햇빛: ${khb_count}개"
            echo "* 이승연: ${lsy_count}개"
            echo "* 오완진: ${owj_count}개"
            echo "* 문세희: ${msh_count}개"
            echo
            echo "--"
            echo
          } > COUNT.md
          
          if [ -f temp.md ]; then
            cat temp.md >> COUNT.md
            rm temp.md
          fi
          
          git config --global user.name "shmm0320"
          git config --global user.email "shmm0320@gmail.com"
          
          git add COUNT.md
          if git diff --staged --quiet; then
            echo "No changes"
            exit 0
          else
            git commit -m "Update weekly problem count"
            git push origin main
          fi
